Passenger service task
aleshkey/cab-system pull request #1
Opened 2024-03-26 08:00 UTC by aleshkey

2024-03-26 21:13 UTC, AbandonedScope requested changes

2024-03-26 21:13 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/controller/PassengerController.java
> +        passengerService.savePassenger(modelMapper.map(passengerDTO, Passenger.class));
Маппинг должен быть в сервисах, т.к. это часть бизнес логики

2024-03-26 21:20 UTC, aleshkey commented on passenger-service/src/main/java/passenger/service/dto/PassengerDTO.java
> +    @Min(value = 0, message = "rating cant be less then zero")
А можно пример данных способов, а то не очень понял😅

2024-03-26 21:26 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/dto/PassengerDTO.java
> +    @Min(value = 0, message = "rating cant be less then zero")
https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/docs/i18n.md

2024-03-26 21:28 UTC, aleshkey commented on passenger-service/src/main/java/passenger/service/dto/PassengerDTO.java
> +    @Min(value = 0, message = "rating cant be less then zero")
Спасибо большое)

2024-03-28 07:25 UTC, AbandonedScope requested changes

2024-03-28 07:25 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/controller/PassengerController.java
> +        return new ResponseEntity<>(new MessageResponse(SuccessMessageConstants.UPDATE_SUCCESS.getValue()), HttpStatus.OK);
Можно возвращать обновлённую сущность

2024-03-28 07:25 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/handler/PassengerControllerAdvice.java
> +        return new ResponseEntity<>(new ErrorResponse(exception.getMessage()), HttpStatus.NOT_FOUND);
Как раз наоборот, лучше использовать статические методы, а не конструктор

2024-03-28 07:25 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/service/PassengerService.java
> +    public PassengerListDto getPage(int num){
А если num равно 0? -1?

2024-03-28 07:59 UTC, AbandonedScope requested changes

2024-03-28 07:59 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/controller/PassengerController.java
> +        ResponseEntity<Object> errors = responseErrorValidator.mapValidationService(bindingResult);
Валидационные ошибки отлавливай через `@RestControllerAdvice`

2024-03-28 07:59 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/controller/PassengerController.java
> +        ResponseEntity<Object> errors = responseErrorValidator.mapValidationService(bindingResult);
Валидационные ошибки отлавливай через `@RestControllerAdvice`

2024-03-28 07:59 UTC, AbandonedScope commented on passenger-service/src/main/java/passenger/service/service/PassengerService.java
> +        if(page.getContent().isEmpty()) throw new PageNotExistException(num);
Не, так не стоит делать
Просто возвращай пустую страницу

2024-03-28 08:29 UTC, aleshkey commented on passenger-service/src/main/java/passenger/service/service/PassengerService.java
> +        if(page.getContent().isEmpty()) throw new PageNotExistException(num);
Оно в прошлый раз просто возвращало пустой лист, поэтому и решил так сделать

2024-03-28 09:41 UTC, AbandonedScope approved these changes

2024-03-28 10:19 UTC, merged